// OPERADORES LOGICOS

// AND -> &&
// OR -> ||
// NOT -> !

// VERIFICA QUE 2 CONDICIONES SEAN CIERTAS, EN DADO CASO DE QUE ALGUNA DE ELLAS
// NO SEA CIERTA ARROJARÁ UN FALSE
// console.log(5<3 && 6>2);

// .OR TE VA A DAR UN TRUE EN CASO DE QUE ALGUNA DE LAS 2 COMPARACIONES SEA CIERTA
// console.log(5>3 || 6<2);

// NOT ES UNA CONTRADICIÓN
// console.log(!4>2);

// COMBINACIÓN DE OPERADORES LOGICOS
console.log(2>3 && 3>4 || 4>2 || !1>2);