// ESTABLECEMOS UNA VARIABLE
var cuatro = 4;



// NOTA: NOMBRAR A TUS VARIABLES DEPENDIENDO DE LO QUE VAS A GUARDAR EN ELLAS, QUE TENGA SIGNIFICADO
// CON LO QUE VAS A GUARDAR EN ESA VARIABLE
var encryptpassword = 'fsdjfkalsdfjsdkl';

// CAMELCASE
var encryptPaswword = 'dfsdfsdafsd';

// UNDERSCORE
var encrypt_password = 'fdssdfsd';

// REASIGNACIÓN DE VARIABLES
var dos = 2;
dos = 4;

// IMPRIMIR EL VALOR DE LA VARIABLE EN LA CONSOLA
console.log(dos);


// COMO BUENA PRACTICA NO OLVIDES TU ; AL FINAL DE CADA LÍNEA DE CÓDIGO